name: .NET

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x
          dotnet-quality: ga

      - name: Restore tests
        run: dotnet restore ./tests/BenchmarkDotNet.ReportColumns.Tests.csproj

      - name: Build tests
        run: dotnet build ./tests/BenchmarkDotNet.ReportColumns.Tests.csproj -c Release --no-restore

      - name: Test
        run: dotnet test ./tests/BenchmarkDotNet.ReportColumns.Tests.csproj -c Release --no-build --verbosity normal

  publish:
    name: Pack & Publish
    runs-on: ubuntu-latest
    needs: test

    # publish ONLY on push to main (never on PR)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: ga

      - name: Restore
        run: dotnet restore ./src/BenchmarkDotNet.ReportColumns.csproj

      - name: Build
        run: dotnet build ./src/BenchmarkDotNet.ReportColumns.csproj -c Release --no-restore

      - name: Pack
        run: dotnet pack ./src/BenchmarkDotNet.ReportColumns.csproj -c Release --no-build -o ./artifacts

      - name: Pack
        run: dotnet pack ./src/BenchmarkDotNet.ReportColumns.csproj -c Release -o ./artifacts

      - name: NuGet login
        uses: NuGet/login@v1
        with:
          user: alexeyfv

      - name: Push to NuGet.org
        run: dotnet nuget push "./artifacts/*.nupkg" --source https://api.nuget.org/v3/index.json --skip-duplicate
