name: CI

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x
          dotnet-quality: ga

      - name: Restore tests
        run: dotnet restore ./tests/BenchmarkDotNet.ReportColumns.Tests.csproj

      - name: Build tests
        run: dotnet build ./tests/BenchmarkDotNet.ReportColumns.Tests.csproj -c Release --no-restore

      - name: Test
        run: dotnet test ./tests/BenchmarkDotNet.ReportColumns.Tests.csproj -c Release --no-build --verbosity normal

  publish:
    name: Pack & Publish
    runs-on: ubuntu-latest
    needs: test

    # publish ONLY on tag push like v0.1.2
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: ga

      - name: Compute version from tag
        id: ver
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Restore
        run: dotnet restore ./src/BenchmarkDotNet.ReportColumns.csproj

      - name: Build
        run: dotnet build ./src/BenchmarkDotNet.ReportColumns.csproj -c Release --no-restore -p:Version=${{ steps.ver.outputs.VERSION }}

      - name: Pack
        run: dotnet pack ./src/BenchmarkDotNet.ReportColumns.csproj -c Release --no-build -o ./artifacts -p:PackageVersion=${{ steps.ver.outputs.VERSION }}

      - name: NuGet trusted publishing
        uses: NuGet/login@v1
        id: nuget_login
        with:
          user: alexeyfv

      - name: Push to NuGet.org
        run: dotnet nuget push "./artifacts/*.nupkg" -s https://api.nuget.org/v3/index.json --api-key "${{ steps.nuget_login.outputs.NUGET_API_KEY }}" --skip-duplicate
