name: .NET

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x
          dotnet-quality: ga

      - name: Restore tests
        run: dotnet restore ./tests/BenchmarkDotNet.ReportColumns.Tests.csproj

      - name: Build tests
        run: dotnet build ./tests/BenchmarkDotNet.ReportColumns.Tests.csproj -c Release --no-restore

      - name: Test
        run: dotnet test ./tests/BenchmarkDotNet.ReportColumns.Tests.csproj -c Release --no-build --verbosity normal

  publish:
    name: Pack & Publish
    runs-on: ubuntu-latest
    needs: test

    # publish ONLY on push to main (never on PR)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: ga

      - name: Restore
        run: dotnet restore ./src/BenchmarkDotNet.ReportColumns.csproj

      - name: Build
        run: dotnet build ./src/BenchmarkDotNet.ReportColumns.csproj -c Release --no-restore

      - name: Pack
        run: dotnet pack ./src/BenchmarkDotNet.ReportColumns.csproj -c Release --no-build -o ./artifacts

      - name: Add GitHub Packages source
        run:
          dotnet nuget add source "https://nuget.pkg.github.com/alexeyfv/index.json" \
          --name github \
          --username "alexeyfv" \
          --password "${{ secrets.GITHUB_TOKEN }}" \
          --store-password-in-clear-text

      - name: Push
        run: dotnet nuget push "./artifacts/*.nupkg" --source github --skip-duplicate
